### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by jacoblindblad** [annaehrnsperger/kwera#6]
Tracking would be great. 
Perhaps we don't need to go evil Google Analytics. I have tried goatcounter.com for a smaller project recently, and it worked ok (not perfect). Perhaps you know of some other tools that anonymise users and don't sell their souls?

**Comment by annaehrnsperger** [comment]
Not a big fan of Google Analytics as well. I usually recommend Netlify Analytics https://www.netlify.com/products/analytics/ 
It's great because, it happens serverside, so we don't need to include a script on the client. The data is more accurate that way as well. And the site is deployed on Netlify so there is not yet another service involved. I use it myself on/off – it's 9$/month. 

I haven't found anything good for free so far and there is certainly a reason why so many tracking services cost something. Especially when it comes to user data ... I'm more for implementing something good that gives great value, otherwise we might just leave it out.
